### ISSUE TITLE
Add additional features

### ISSUE THREAD

**Issue by zdykstra** [humdingerb/UploadIt#1]
Thanks for this great little tool! I've added a few additional features in https://github.com/zdykstra/UploadIt/tree/notifications-and-zip .  

* I've switched a couple of the messages that were previously copied to the clipboard to instead be notifications. 
* Directory uploading support has been added by feeding the directory path to `zip` and then sending that processes stdout to `curl`. 
* While uploads are taking place, a notification pops up to indicate that it's happening.

Is there any interest in seeing some/all of these changes merged into your release? There's a new string ("Uploading") used, so getting that translated is hopefully not too difficult - but I have no experience with that process.

**Comment by humdingerb** [comment]
Generally, these are nice changes and very welcome. There are just a few changes, I'd like to make. You can do those and create a PR, or PR the current state and I take care of that.

To avoid having "UploadIt" twice in the notification, keep it as the "Group" label and use the "Title" for "Uploading:" or "Finished uploading:", and as "Content" the path.Leaf().

For larger uploads, the default timeout is too short. Use "notification.Send(600000000);" while uploading to keep the notification visible for 10*60 seconds.

I'm not sure that it makes sense to set WebPositive as "SetOnClickApp". Clicking it will open web+ start downloading immediately what you just uploaded.

I suppose getting at the progress percentage isn't easily done... :)

**Comment by zdykstra** [comment]
I'm happy to make the requested changes and open a PR with them for review.

I thought about trying to enable a progress bar in `curl` and then parse that - but that will fall apart when uploading a directory since the data is coming in over stdin. `UploadIt` would have to create a temporary zip file on disk first so that `curl` knew the exact size of the file it was uploading. I'm not sure that's worth it.

As far as the OnClick handler, I don't have a great justification for that. I think I added it more 'because I could' than anything else. With that said, are there any OnClick behaviors that do make sense? There's little reason to open the parent directory in Tracker; you have to be there already to call the add-on.

**Comment by humdingerb** [comment]
OK, great!
It's OK not to have a progress indicator, I think. UploadIt is using free temp hosters, people shouldn't upload huge files anyway, plus those get deleted sooner the bigger they are. So, I expect the typical upload not taking so long that a progress bar becomes important.
I'd say remove the OnClick behaviour. Nothing really seems to be useful.
